add ggg-kat-geor-latn-2002, closes #115
interscript/interscript-ruby pull request #220
Opened 2020-02-06 16:58 UTC by antonsviridenko

2020-02-07 02:40 UTC, ronaldtse requested changes

2020-02-07 02:40 UTC, ronaldtse commented on maps/ggg-kat-geor-latn-2002.yaml
> +    '\u10d0' : 'a' # ა
The map isn't working because in YAML, `'\u10d0' :` needs to be `'\u10d0':`. There should not be a whitespace between the key and the colon.

2020-02-07 16:56 UTC, antonsviridenko commented on maps/ggg-kat-geor-latn-2002.yaml
> +    '\u10d0' : 'a' # ა
ok,
I used un-rus-Cyrl-Latn-1987 map file as an example,
it also has whitespace and therefore should be invalid too then

https://github.com/riboseinc/interoperable-transliteration/blob/master/maps/un-rus-Cyrl-Latn-1987.yaml#L161

2020-02-07 17:21 UTC, ronaldtse commented on maps/ggg-kat-geor-latn-2002.yaml
> +    '\u10d0' : 'a' # ა
Strange; that is really supposed to fail...

2020-02-07 17:21 UTC, ronaldtse commented
@andrew2net can you have a look at this PR? Thanks!

2020-02-07 17:30 UTC, chaaklau commented
There is an extra - on this line:


- expected: baq’aq’i


On Sat, 8 Feb 2020 at 1:21 AM, Ronald Tse <notifications@github.com> wrote:

> @andrew2net <https://github.com/andrew2net> can you have a look at this
> PR? Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/riboseinc/interoperable-transliteration/pull/220?email_source=notifications&email_token=ABHHW7OCTYR6HOQ3RIXVRDLRBWKCFA5CNFSM4KRAP2RKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELD2RWQ#issuecomment-583510234>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABHHW7LCLB3WQBVXTZHBMULRBWKCFANCNFSM4KRAP2RA>
> .
>

2020-02-07 17:36 UTC, antonsviridenko commented
@chaaklau hmm, yeah, right, thank you

2020-02-08 08:33 UTC, andrew2net commented on maps/ggg-kat-geor-latn-2002.yaml
> +  - expected: baq’aq’i
There is an extra `-` in the last test. I've fixed it.

2020-02-08 08:34 UTC, andrew2net commented
LGTM

2020-02-08 08:42 UTC, ronaldtse approved these changes

2020-02-08 08:44 UTC, ronaldtse commented
Thanks guys!! While we're at it, these are the other Georgian systems to be done:
* #114 
* #113 
* #112 

They must be quite similar.

2020-02-08 08:45 UTC, merged