#263 #269 #270 #272 #279 odni systems
interscript/interscript-ruby pull request #316
Opened 2020-07-17 15:40 UTC by CAMOBAP

- #263
 - #269 
 - #270 
 - #272 
 - #279

2020-07-17 16:07 UTC, ronaldtse commented
Thank you @camobap!

I see that the systems only have minimal tests. Could you help make up some additional tests so that the systems can be well tested and remain stable even if someone else changes the rules? Thanks!

2020-07-17 21:44 UTC, antonsviridenko requested changes

2020-07-17 21:44 UTC, antonsviridenko commented on maps/odni-bel-Cyrl-Latn-2015.yaml
> +name: Office of the Director Of National Intelligence Georgian Personal Names 2015, ICS 630-01 Annex B
"Georgian Personal Names" - it should be "Belarusian Personal Names" here. Same in other files

2020-07-18 01:51 UTC, ronaldtse commented on maps/odni-bel-Cyrl-Latn-2015.yaml
> +name: Office of the Director Of National Intelligence Georgian Personal Names 2015, ICS 630-01 Annex B
Thank you @antonsviridenko you have a very sharp eye 😉

2020-07-18 20:39 UTC, CAMOBAP commented on maps/odni-bel-Cyrl-Latn-2015.yaml
> +name: Office of the Director Of National Intelligence Georgian Personal Names 2015, ICS 630-01 Annex B
Done

2020-07-19 06:27 UTC, CAMOBAP commented
More tests added

2020-07-19 09:26 UTC, merged