Updates and fixes on un-mon-Mong-Latn-2013
interscript/interscript-ruby pull request #477
Opened 2020-09-28 06:42 UTC by javkhaanj7

Added more tests and updates map characters. This will fix https://github.com/interscript/interscript/issues/37 and https://github.com/interscript/interscript/issues/415 issues

2020-09-28 10:13 UTC, ronaldtse requested changes
The UN Mongolian Old Script system is based on Pinyin characters. Can we make sure the transliterated names fit according to spec? Thanks!

2020-09-28 10:13 UTC, ronaldtse commented on maps/un-mon-Mong-Latn-2013.yaml
> +  - A separated final form of vowels a or e is common, and can appear at the end
@javkhaanj7 can you move these notes as a new key `implementation_notes:` so that these are linked as implementation notes, not the notes of the specification? Thanks.

2020-09-28 10:13 UTC, ronaldtse commented on maps/un-mon-Mong-Latn-2013.yaml
> +    expected: bayannaɣur qota
The `ᠭ` character seems to be transliterated as `ɣ`. According to the spec it should be `g`?

<img width="94" alt="Screen Shot 2020-09-28 at 3 20 23 PM" src="https://user-images.githubusercontent.com/11865/94402078-227cd900-019e-11eb-8dca-7a97195f94ab.png">

2020-09-28 10:14 UTC, ronaldtse commented
The official spec for the system is this: 
[e_conf_74_L48.pdf](https://github.com/interscript/interscript/files/5291492/e_conf_74_L48.pdf)

2020-09-29 18:42 UTC, ronaldtse commented on maps/un-mon-Mong-Latn-2013.yaml
> +    expected: bayannaɣur qota
Ah, the ɣ character is used in the VMPC transliteration system. So the code here should be moved to #482

2020-10-02 06:20 UTC, ronaldtse commented
@javkhaanj7 could you help revert the rule changes of this system, and convert the examples to this system? Thanks.

2020-10-03 09:43 UTC, javkhaanj7 commented
@ronaldtse fixed the issues, please check.

2020-10-04 07:06 UTC, ronaldtse commented
Thank you @javkhaanj7 !

2020-10-04 07:06 UTC, merged