Odni fas arab latn 2015
interscript/interscript-ruby pull request #510
Opened 2020-10-04 20:21 UTC by AhMohsen46

2020-10-06 08:26 UTC, ronaldtse requested changes

2020-10-06 08:26 UTC, ronaldtse commented on maps/odni-fas-Arab-Latn-2015.yaml
> +language: ics-630-01:prs
`language: iso-639-2:fas`

2020-10-06 08:26 UTC, ronaldtse commented on maps/odni-fas-Arab-Latn-2015.yaml
> +    - Alef maqsura (final yeh pronounced as a long “a”) should
Can we split these into multiple notes?

2020-10-06 08:26 UTC, ronaldtse commented on maps/odni-per-Arab-Latn-2015.yaml
> +source_script: Afghan (Dari)
This has to be a 15924 code, so it would be `Arab`.

2020-10-06 08:26 UTC, ronaldtse commented on maps/odni-fas-Arab-Latn-2015.yaml
> +source_script: Persian (Farsi)
This is still `Arab` even though it feels wrong...

2020-10-06 08:26 UTC, ronaldtse commented on maps/odni-per-Arab-Latn-2015.yaml
> +language: ics-630-01:prs
`language: iso-639-3:prs`

2020-10-06 08:26 UTC, ronaldtse commented on maps/odni-per-Arab-Latn-2015.yaml
> +  - |
Please split into multiple notes.

2020-10-06 11:26 UTC, AhMohsen46 commented on maps/odni-fas-Arab-Latn-2015.yaml
> +    - Alef maqsura (final yeh pronounced as a long “a”) should
yes sure, will do that now

2020-10-06 11:31 UTC, AhMohsen46 commented on maps/odni-per-Arab-Latn-2015.yaml
> +source_script: Afghan (Dari)
@ronaldtse 
so it'd be like this
language: iso-639-2:dari
source_script: Arab
?

2020-10-07 10:29 UTC, ronaldtse commented
Thank you @AhMohsen46 !

2020-10-07 10:29 UTC, merged