bgnpcgn-urd-Arab-Latn-2007
interscript/interscript-ruby pull request #573
Opened 2020-10-18 10:07 UTC by AhMohsen46

2020-10-18 22:18 UTC, AhMohsen46 commented
blocked by #572

2020-10-20 07:57 UTC, ronaldtse requested changes
@AhMohsen46 could you have a look at the comments? Thanks!

2020-10-20 07:57 UTC, ronaldtse commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +language: iso-639-3:prs # prs stands for Dari (https://iso639-3.sil.org/code/prs&_ga=GA1.2.2054538372.1574092823)
Change to `iso-639-2:urd`?

2020-10-20 07:57 UTC, ronaldtse commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +  # - source: بوغدِی
Are these working, or to be done?

2020-10-20 09:29 UTC, AhMohsen46 commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +language: iso-639-3:prs # prs stands for Dari (https://iso639-3.sil.org/code/prs&_ga=GA1.2.2054538372.1574092823)
yes sure, will do this immediately

2020-10-20 09:34 UTC, AhMohsen46 commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +  # - source: بوغدِی
so, the commented out examples, are from the docs, however, they are dependent on the cases in the blocking issue, as soon as it's resolved, the examples will be uncommented and should be okay to run without failing

2020-10-20 23:18 UTC, ronaldtse commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +  # - source: بوغدِی
In this case can you add the link to the blocking issue inside the comment so people reading the map can know this? Thanks!

2020-10-21 11:51 UTC, AhMohsen46 commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +  # - source: بوغدِی
yes, this makes perfect sense, will do it immediately

2020-10-21 11:59 UTC, AhMohsen46 commented on maps/bgnpcgn-urd-Arab-Latn-2007.yaml
> +  # - source: بوغدِی
done

2020-10-23 03:37 UTC, ronaldtse commented
@AhMohsen46 the specs should be working now, could you help rebase? Thanks!

2020-10-25 11:59 UTC, AhMohsen46 commented
@ronaldtse rebased, pushed
all good to go except for #572

2020-10-25 15:51 UTC, ronaldtse commented
Thanks @AhMohsen46 !

2020-10-25 15:51 UTC, merged