WIP add iso-ara-Arab-Latn-223-1993
interscript/interscript-ruby pull request #703
Opened 2021-05-03 11:23 UTC by AhMohsen46

2021-05-03 15:16 UTC, ronaldtse requested changes

2021-05-03 15:16 UTC, ronaldtse commented on maps/iso-ara-Arab-Latn-233-1993.yaml
> +url: https://cdn.standards.iteh.ai/samples/4118/2f03c828842c4055a5619c1bded39381/ISO-233-2-1993.pdf
Please change this to the official ISO url.

2021-07-03 08:32 UTC, ronaldtse commented
@AhMohsen46 are we ready to merge this? Thanks.

2021-07-04 23:49 UTC, AhMohsen46 commented
Yes I believe this is complete
Will check the docs the earliest next morning (in 6 hours at most)

2021-07-04 23:50 UTC, ronaldtse commented
I've migrated this to the new structure here: interscript/maps#3 . Closing this.

2021-07-04 23:50 UTC, closed without merging